#
# This source file is part of the Stanford Biodesign Digital Health Spezi Web Configurations open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Deployment

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  publishpackage:
    name: Publish Package
    uses: StanfordBDHG/.github/.github/workflows/npm-publish-package.yml@v2
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      packageVersion: ${{ github.event.release.tag_name }}
